// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8_3ZCG9oK0jjVXU37xibdb-T7WmUSJyw',
    appId: '1:857806984296:web:ed50c7f26bc378ee2697dd',
    messagingSenderId: '857806984296',
    projectId: 'desafio-quality',
    authDomain: 'desafio-quality.firebaseapp.com',
    storageBucket: 'desafio-quality.appspot.com',
    measurementId: 'G-XCEFFM6S4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtTyp0yLM3hdWjWzy4etSsOENauJcUX0k',
    appId: '1:857806984296:android:53f9be790d3e030b2697dd',
    messagingSenderId: '857806984296',
    projectId: 'desafio-quality',
    storageBucket: 'desafio-quality.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8_3ZCG9oK0jjVXU37xibdb-T7WmUSJyw',
    appId: '1:857806984296:web:ddefc6d59f9ed38c2697dd',
    messagingSenderId: '857806984296',
    projectId: 'desafio-quality',
    authDomain: 'desafio-quality.firebaseapp.com',
    storageBucket: 'desafio-quality.appspot.com',
    measurementId: 'G-V4KKM88ZF5',
  );
}
